version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12-browsers
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: make setup
      # - save_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      #     paths:
      #       - node_modules
      - run: make typecheck
      - run: make test
      - run: make lint
      - run: make benchmark

