version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: make setup
      # - save_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      #     paths:
      #       - node_modules
      - run: make typecheck
      - run: make test-ci
      - run: make lint
      - run: make benchmark-ci
      - run: make bundle
      - run: make check-bundle
      - run: ls -sS1h lib/ | grep bundle.js

